### ISSUE TITLE
Not able to login first time

### ISSUE THREAD

**Issue by whaleloops** [wandb/local#25]
### Problem
wandb local creates the container but the index page localhost:8080 does not load.
![image](https://user-images.githubusercontent.com/31370581/125351423-124d7900-e32e-11eb-940a-6b82bdf22d60.png)

### Follow
Already upgrade to the newest version.
docker logs -f wandb-local
![Screenshot from 2021-07-13 12-58-50](https://user-images.githubusercontent.com/31370581/125494992-5dd1878a-59c2-4abd-a0a7-8a3c59b9b8a6.jpg)

I compared this above with another successful install on my own ubuntu machine, difference is shown in red.

Seems like a MySQL connection issue. Any solutions?

**Comment by vanpelt** [comment]
@whaleloops the fatal error is due to the MySQL server running inside of the container crashing.  You can exec into the container to get the MySQL log with:

```
docker exec -it wandb-local bash
tail -n 1000 /var/log/mysql.log
```

My guess is either issues with the filesystem which you could resolve by changing the file system driver docker is using, or the container can't get enough memory / cpu.  Where are you running the container?

**Comment by whaleloops** [comment]
Thanks for the timely reply. 
I was trying to set this up on a private redhat offline server with 32+ cpus and 500gb+ memory. I do not have sudo access but have only privilege docker access. Could you elaborate on "could resolve by changing the file system driver docker is using"?

After running this below, I got:
docker exec -it wandb-local bash
tail -n 1000 /var/log/mysql.log

![image](https://user-images.githubusercontent.com/31370581/125386803-e2709680-e36a-11eb-8070-b31c4ee5cd9e.png)

**Comment by whaleloops** [comment]
I also make sure that mysql in the docker container **could start** from 127.0.0.1

**Comment by vanpelt** [comment]
There should be more tables than is shown there.  It looks like the initial migration failed, a fully migrated database will have ~69 rows from the table query.  If you do `SELECT * FROM schema_migrations` you'll likely see the "dirty" column has a "1" in it.  The easiest solution is to remove the existing volume and boot the instance again since you don't have any data written to it.

```
docker stop wandb-local
docker volume rm wandb
wandb local
```

Then you can look at the logs of the container and it should say "Migrating database..." without any errors.

The volume driver options I mentioned can be found here: https://docs.docker.com/storage/storagedriver/select-storage-driver/

You can see what storage driver is being used by running `docker info`.  It looks like older version of RHEL didn't support overlay2 which is the preferred driver, but newer versions do.

**Comment by whaleloops** [comment]
I just removed wandb volume and started again. It still have the exact same issue
```
docker stop wandb-local
docker volume rm wandb
docker load --input path/to/docker//wandb_local.tar
wandb local
```

**Comment by whaleloops** [comment]
Where does /var/log/gorilla.log come from? What is the corresponding library? Multiple error existed within this file.

**Comment by vanpelt** [comment]
That's our internal service written in golang.  It's what speaks to MySQL and provides our graphql API.  The issue is likely due to this line `docker load --input path/to/docker/wandb_local.tar`.  You should ensure the image you're running is a carbon copy of what's on dockerhub without any local filesystem changes.  Why are you loading from a tarball?

**Comment by whaleloops** [comment]
I used "docker save --output wandb_local.tar wandb/local" on my machine with internet to download and then USB into the server without internet.

**Comment by vanpelt** [comment]
Just make sure that you aren't saving a running version of wandb/local.  It should only be the fresh state from docker.  Can you share the full contents of `/var/log/mysql.log` for the instance that's failing to start up?

**Comment by whaleloops** [comment]
This is the full content

![image](https://user-images.githubusercontent.com/31370581/125997008-934558e0-d047-43e4-9162-4c7371740496.png)

with "[Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details)." above

**Comment by vanpelt** [comment]
That warning is fine.  What do you get when you connect to the database and check the schema with `SELECT * FROM schema_migrations`?  The initial migration is failing and likely marking a specific migration as failed for reasons that are not yet clear.  Knowing which migration failed will help us figure out why MySQL can't be migrated.

**Comment by whaleloops** [comment]
![image](https://user-images.githubusercontent.com/31370581/126207875-1dc168ce-82ec-45b1-a10b-89f587c394cc.png)

**Comment by vanpelt** [comment]
Yep, something is causing the migration or MySQL to crash.  We have 118 migrations so it's really strange it crashed so early.  Migration number 2 is actually just:

```
ALTER TABLE runs ADD COLUMN deleted_at datetime DEFAULT NULL;
```

You could try running that statement on the db, and then running `UPDATE schema_migrations SET dirty=0`, then restarting the docker container will trigger the migrations to continue running on initial boot.

**Comment by whaleloops** [comment]
I did what you suggested.
And then the docker logs became
![Screenshot from 2021-07-23 15-44-32](https://user-images.githubusercontent.com/31370581/126834749-23c09955-318a-47d4-9294-dc14bc0ae2fb.png)

select * from schema_migrations;
now has version 3 and dirty 1 on it.

It seems that for some reason, I could only execute this one step/migration at a time.

**Comment by whaleloops** [comment]
Also when I tried to update mysql manually each time: it told me that the execution already happened. It seems that the code doesn't know to continue.
![Screenshot from 2021-07-23 15-47-27](https://user-images.githubusercontent.com/31370581/126835115-0891628d-717a-4a9f-a569-e62bfc925c20.png)

**Comment by whaleloops** [comment]
I did it again, now within mysal:

```
select * from schema_migrations;
```
now has version 5 and dirty 1 on it.

You mentioned that there are 118 migrations? Any ways that I don't have to repeat 100+ times? 
Could it be the docker version is too early? My docker version is 1.13.1 from year 2018.

**Comment by vanpelt** [comment]
Yeah, there's definitely something wrong with either your docker version or the system resources be allocated to the instance.  Can you try launching this on a larger machine using a new version of docker?  You should never need to issue these queries manually.  If the automatic migration fails it indicates there's something wrong with docker / your hardware.

**Comment by whaleloops** [comment]
Unable to resolve, end up using ray instead. Is there a way to easily visualize ray hyperparam tuning results like wandb? (param importance and etc.)

**Comment by ant1s** [comment]
> Unable to resolve, end up using ray instead. Is there a way to easily visualize ray hyperparam tuning results like wandb? (param importance and etc.)

I met the problem exactly as yours these days, and finally I solved this problem by copying /vol data from another successful initialized machine
