### ISSUE TITLE
Local Server points to localhost when trying to download artifacts

### ISSUE THREAD

**Issue by serchu** [wandb/local#37]
I have a running local instance in my PC with Docker. `wandb local` and everything works fine: people can connect to it from **other machines** by pointing to my IP, accessing to the web service and using Python to upload data to a run.

The only thing that is not working is when trying to download an artifact (with several files), the execution either gets blocked or it just downloads a 1-byte file. Same when trying to download any file of an artifact from the web dashboard: it tries to download the file by pointing to localhost:8080/ so it cannot resolve it.

From my local PC, everything works: Both web and Python scripts.
Thanks in advance.

**Comment by vanpelt** [comment]
You should configure a load balancer in front of the container and configure DNS.  You're also risking data loss by not licensing and connecting external MySQL and S3 storage.  All that being said, you likely want to update the Host setting at /system-admin to point to your external IP instead of localhost.

**Comment by serchu** [comment]
Thank you very much! /system-admin was all I needed to setup that.
