### ISSUE TITLE
Cannot log large artifact files ~700mb using private cloud Terraform-Azure installation

### ISSUE THREAD

**Issue by hrabago** [wandb/local#58]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/16505696/156414234-266e2afa-89c5-48d7-9119-2e3ae910de5d.png">

- using wandb-local:0.9.49 also tried 0.9.48

Hello,

Model training and logging of small artifact files works fine, but when I try to log a large model file to artifacts the upload process gets stuck in a loop. It usually uploads around 150 mb of the 765mb file, and then it restarts from 0. Eventually it shows a networkError as seen in the screenshot.

Here's the error I found on the debug-internal.log file:
`2022-03-02 12:34:02,750 ERROR   Thread-14 :61193 [internal_api.py:upload_file():1203] upload_file exception <my azure blob storage url>('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))`

Thanks for your help,
Hector

**Comment by vanpelt** [comment]
Hey @hrabago this was fixed in the most recent version of our client library.  With versions of the wandb client < 0.12.11 the maximum size of an artifact that can be uploaded to azure storage was 256mb.  The new logic supports files up to a terrabyte.  You'll also need to have the azure sdk installed for the logic to work, you can get it with:

```
pip install --upgrade wandb[azure]
```

Let me know if that resolves the problem!

**Comment by hrabago** [comment]
Yes, that worked! Thank you so much @vanpelt!
